// ignore: file_names
enum AdminPage {
  homepage,
  userList,
  adduser,
  creatoruserlog,
  currencysetup,
  emailsetting,
  addingamount,
  addingpayment,
  userlogs,
  transaction,
  wallettransaction,
  basicsetting,
  terms,
  privacy,
  support, 
  branduser,
  creatoruser,
  adminuser,
  employeeuser,
  adminuserlog,
  employeeuserlog,
  appsetting,
  brandsetting,
  currencysetting,
  notificationsetting,
  notificationtemplates,
  smssetting,
  paymentsetting,
  systemsetting,
  brandtransaction,
    // 👇 ADD THESE
  brandcampaign,
  brandwisecampaignlist,
  campaigndetails,

  creatorcampaigntracking,
  creatorservicetracking,
  creatoreacrning,

  instagracategorylist,
}
